### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by MtFBella109** [Thive-N/nixdots#1]
I get directly this Error: `error: undefined variable 'system'

       at /nix/store/w1rvhfrfd8mwvh6phh4wvq21q2di7pa3-source/flake.nix:27:42:

           26|     nixosConfigurations = {
           27|       desktop = nixpkgs.lib.nixosSystem {
             |                                          ^
           28|         inherit system;`

**Comment by Thive-N** [comment]
The version i had on my system differed from the one on github

ive updated this repo so its up to date with my system and it should fix your problem
